### ISSUE TITLE
How'd you find this?

### ISSUE THREAD

**Issue by pfeiferchristopher** [ilendemli/gumer-psn-php#14]
Where did you find the Docs to pull from api.sonyentertainmentnetwork.com? The reason I ask is I'm currently building a gaming social platform that and have already built in Xbox LIVE integration and am now looking for PlayStation Network and will then work on the Steam Network.

I am an avid PHP programmer and am very interested in helping out with this project but I'd like to know more about how you came about it as to make sure it isn't something that will break shortly after I'm implemented it.

**Comment by D-Pyro** [comment]
Pretty sure this is reverse engineered from the official app.

**Comment by pfeiferchristopher** [comment]
Ah very nice.

**Comment by xXREDXIIIIXx** [comment]
Yes this is taken from the playstation APP so if they ever change the way the APP works the code will need to be re-worked (the login token system has changed a couple of times I believe)

I currently use this on my website with great success. I have also added a few things to my site that are not included in this build but it is all in the previous version of the code (v0.1).

The author ilendemli was very helpful with getting me going.

**Comment by ilendemli** [comment]
this API has been ported from https://github.com/jhewt/gumer-psn to PHP which has been created by reverse engineering the official PSN app for Android but I also have added more functionality to it by setting up a proxy and sniffing the secure connection.

**Comment by norwack** [comment]
@ilendemli If i may ask, what tools did you use to sniff the traffic on android and how did you decrypt it? Assuming it's using SSL.

**Comment by ilendemli** [comment]
i don't have any Android devices, but you can decompile Android apps, thats how José reverse engineered it. I have installed the Charles proxy tool on my pc, installed the Charles certificate on my phone (I have an iOS device) and looked through the data to replicate it using php

**Comment by VileTung** [comment]
Fiddler can do the same, that's how I did it, hoping to find something to get the secret trophy data :/

**Comment by xXREDXIIIIXx** [comment]
Yeah would be nice to see the hidden trophies but thats not how the server sends the information unfortunately. but I made the most of it I just showed them as hidden on my site and once its unlocked others can view it :)

**Comment by jhewt** [comment]
I know is a lil bit late but I found SONY's API using what @VileTung suggested. Fiddler 2 was very easy to use and you can easily install a self-signed certificate in Android.
However, I also did reverse engineering by decompiling the APP. Reading the webview's JS code and reading smali (similar to ASM) to see what else I can add to the API like the PS4 features (Wake up, run a game, etc) and also finding the HMAC key to generate some URLs.

**Comment by pfeiferchristopher** [comment]
Wow never would have thought about how their App does it.
